export type RootStackParamList = {
    Dashboard: undefined;
    Home: undefined;
    CreateDelivery: undefined;
    FindingDriver: undefined;
    Tracking: { driver: any };
    Chat: undefined;
    DeliveryCompletion: undefined;
    Wallet: undefined;
    BillPayment: { provider: any };
    Activity: undefined;
    Profile: undefined;
    WalletMain: undefined;
    'Go Online': undefined;
    Earnings: undefined;
    Login: undefined;
    Register: undefined;
    DriverKYC: undefined;
    DriverHome: undefined;
};
